
[functions.create-order]
enabled = true
verify_jwt = false
import_map = "./functions/create-order/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-order/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-order/*.html" ]

[functions.get-album-data]
enabled = true
verify_jwt = false
import_map = "./functions/get-album-data/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-album-data/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-album-data/*.html" ]

[functions.finalize-order]
enabled = true
verify_jwt = false
import_map = "./functions/finalize-order/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/finalize-order/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/finalize-order/*.html" ]

[functions.validate-discount-code]
enabled = true
verify_jwt = false
import_map = "./functions/validate-discount-code/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/validate-discount-code/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/validate-discount-code/*.html" ]

[functions.handle-stripe-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/handle-stripe-webhook/deno.json"
entrypoint = "./functions/handle-stripe-webhook/index.ts"

[functions.create-checkout-session]
enabled = true
verify_jwt = false
import_map = "./functions/create-checkout-session/deno.json"
entrypoint = "./functions/create-checkout-session/index.ts"
